apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: hw2-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw2-app
  template:
    metadata:
      labels:
        app: hw2-app
    spec:
      containers:
      - name: my-app
        image: rmann14/hw2-image
        ports:
        - containerPort: 80