apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw3-deployment
  labels:
    app: hw3-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw3-app
  template:
    metadata:
      labels:
        app: hw3-app
    spec:
      containers:
      - name: my-app
        image: rmann14/hw3-image
        ports:
        - containerPort: 8080
